### ISSUE TITLE
Carb start isn't honored

### ISSUE THREAD

**Issue by csholmq** [Perceptus/GlucoSym#5]
I would expect the following json to start BG to start rising **well after** 25 minutes. `length` doesn't seem to have an impact either.

```
{ "index": 0, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 25, "amt": 100, "length": 10 }] } }
{ "index": 1, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
{ "index": 2, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
{ "index": 3, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
{ "index": 4, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
{ "index": 5, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
{ "index": 6, "time": 60, "dt": 5, "dose": 0.0, "events": { "carb": [{ "start": 0, "amt": 0, "length": 0 }] } }
```

Here's the output:

![screen shot 2018-06-25 at 10 09 03](https://user-images.githubusercontent.com/1297882/41838162-ed0d3f54-785f-11e8-9997-3e5626683fe9.png)

**Comment by bustavo** [comment]
Please take a look at the equations used to model carbs / sensitivities / etc. Again, do not expect the simulation to behave out-of-the-box as your body behaves, you need to tweak the initial conditions.

**Comment by csholmq** [comment]
I don't think this has anything to do with the equations. I read the following and assumed events could be in the future.

> events: You can set events so the simulator will consider them during the run. We recommend to send them on-the-go as your algo will probably be generating these on the run, specifically with the carb part of the events. If you decide to add carbs on-the-go, set the start time at 0 for the new carb being sent so 0 is the time at which the carb was sent to the simulator.

**Comment by bustavo** [comment]
It actually has to do with the equations. The equations model the effect on bg based on the available insulin / carbs / etc. The increase you see may have to do with a combination between lack of insulin at minute 15 and probably afterwards carb effect on blood glucose.

**Comment by csholmq** [comment]
I apologize. This was a combination of me overestimating carb absorption rate and too quickly glancing over the relevant code.

**Comment by bustavo** [comment]
No worries! ☺️ I am aware that the model is not straightforward and requires some fiddling around!

Gustavo M

iPhone. iTypos. iApologize.
